### ISSUE TITLE
Line Length

### ISSUE THREAD

**Issue by ghost** [dwbrite/ajitvpai.com#31]
I think the readability of the site could be improved by reducing the line lenght. [Here](https://material.io/guidelines/style/typography.html#typography-other-typographic-guidelines) is a guideline by Google. (Not really an issue, just a suggestion)

**Comment by unleashy** [comment]
+1 to this. Adding some left and right margins to the content (and "centralizing" it) and diminishing the line length would be nice imo.

**Comment by MrBenJ** [comment]
What do you guys think of wrapping the body in a bootstrap container? This would make it so that on desktop there's some gutters on the sides and centers the content. When made mobile, it'll keep the content naturally at a 15px padding on both the left and right sides.

Also, I'd consider changing the text size to `rem` units, so if users have a preference to larger text size (think grandpa's gigantic text size on his iPhone), it'll automatically adjust to fit :)

**Comment by ghost** [comment]
I don't really know if a bootstrap container is needed because the formatting already works fine. Decreasing  `max-width` to something like `60 rem` would already do the job.
Also: I think the image in the "What are his intentions" section could use `width: 100%` as it currently doesn't scale correctly.
~~One more thing: The red used across the website isn't the same as the one in the comcast/verizon logo.. Not sure if this is intentional because of legal reasons :D~~
Nevermind, I just tested it.. Way too bright to use as a background color.

**Comment by dwbrite** [comment]
> I think the image in the "What are his intentions" section could use width: 100% as it currently doesn't scale correctly.

I believe this issue's been fixed, but the site hasn't gone live yet. Updates to come.

**Comment by MrBenJ** [comment]
Updating everyone on this topic, a pull request was created for this issue. I reviewed it, but there a small problem with it. Waiting on the author to fix it up, then we'll close this issue once merged in and @dwbrite updates the server.

Thank you all for your patience in this
