### ISSUE TITLE
Organization of content

### ISSUE THREAD

**Issue by dwbrite** [dwbrite/ajitvpai.com#33]
We have some great content, but I think the next step is moving it around. We want to create a clear and concise order so things make sense following one another and everything is easy to read and find.

Feel free to post your thoughts below.

**Comment by davecan** [comment]
Might look into how online marketers structure their landing pages -- setting the hook followed by calls to action. This is basically an online marketing site. It promotes a brand (pro-NN) and wants to elicit an emotional reaction (BigCo wants to censor what you can read online and charge you more money for it, etc) followed by taking action (oppose BigCo and the GOP, etc).

**Comment by dwbrite** [comment]
- Who is Ajit Pai
- What are his intentions?
- What can I do?
- What does all this mean?
- Title II
- Net Neutrality
- Footer/Links

**Comment by MrBenJ** [comment]
If any non-developer wants to do a write up for any of the sections and posts it in here, one of the developers like myself can put it into the code for the site.

**Comment by palmerjoshua** [comment]
My proposed order of sections:

* Who is Ajit Pai?
* What is Net Neutrality?
* What is Title II?
* What are Ajit Pai's intentions?
* What does all this mean?
* What can I do?
* Footer/Links

I think we should define net neutrality before explaining all the bad things that could happen without it.

**Comment by CurtisJNeeleyJr** [comment]
Title II is the section of law, the Communications Act of 1934, addressing interstate communications using [common carrier](https://www.law.cornell.edu/uscode/text/47/153#11) [wires](https://www.law.cornell.edu/uscode/text/47/153#59).  

Control of these wires is shared by the public and by corporations who installed these wires on or across public property.  These wires are not controlled by just the free market, but monopolies are allowed like for utilities. This section of US law prevents service providers who use the wires installed on public land from abusing public customers. 

On February [26](https://www.fcc.gov/document/fcc-adopts-strong-sustainable-rules-protect-open-internet), 2015 the FCC admitted the Communications Act classified ISPs under Title II as "_[common carriers](https://www.law.cornell.edu/uscode/text/47/153#11)_", as demanded in the United States Court for the Western District of Arkansas and Eighth Circuit Court of Appeals in:
 _Neeley Jr. v 5 Federal Communications Commissioners. et. al.,_  ([5:14-cv-05135](http://theendofpornbywire.org/index_5135.html))([14-3447](http://theendofpornbywire.org/14-3447/)). 

This publicly announced realization meant the FCC admitted having been given oversight of ISPs by Congress and requiring net neutrality, net safety, and net fairness.  The FCC will eventually regulate pricing for the telecommunications utilities provided by monopoly-like ISPs. 

Interstate Commerce via communications on these "_public_" wires across America is controlled by a Federal Agency ([FCC](https://fcc.gov/)) like transportation on "_public_" rails ([FRA](https://www.fra.dot.gov/)) across America and transportation on "public" airwaves. ([FAA](https://www.faa.gov/)) over America or "_public_" highways ([DOT](https://www.fhwa.dot.gov/)) across America. 

2 + 2 = 4 regardless of what is declared by Chairman Ajit Pai.  Title II overrules Chairman Ajit Pai and explains clearly what telecommunications on the "depression-era" wires will always be. Title II can't be "_revoked_" by any agency and not by Chairman Pai or the whole FCC. This will take Congress or SCOTUS.

I will not again pursue the FCC because I have done this for over six years in federal courts. 

Anyone here may use this information freely.  The docket links above are mirrors giving free links to the filed PDFs and the public non-free PACER links as well. I am not a lawyer.  If you are reading this on "_wireless_" or Wi-Fi you are reading this via the radio apparatus on one end of a wire communication defined exactly in 1934 now existing at 47 USC 153 ¶([59](https://www.law.cornell.edu/uscode/text/47/153#59)).
